### ISSUE TITLE
청원자-청원게시판

### ISSUE THREAD

**Issue by Bobae98** [baekgoms/ProjectB#17]
청원게시판

- 진행중인 청원
- 완료된 청원
   ->답변이 완료된 청원
   ->기간이 만료된 청원
   ->답변을 기다리는 청원

**Comment by Bobae98** [comment]
- [ ] view페이지
- [ ] DB연결

**Comment by hongwoochan1** [comment]
업로드 폼 보완 
MVC 패턴 설정중 
알리아스 디티오 등록

**Comment by Bobae98** [comment]
-진행중인 청원 동의순 최신순보기 버튼구현
-만료된청원, 추가답변 기다리는 청원 SQL, service,impl작성

**Comment by Bobae98** [comment]
petition패키지 병합
만료된 청원 ,답변을 기다리는 청원 DAO작성 & 컨트롤러 작성

**Comment by Bobae98** [comment]
답변기다리는 청원 , 기간 만료된 청원 리스트 DB연동하기
